apiVersion: apps/v1
kind: Deployment
metadata:
  name: neu-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neu-inference
  template:
    metadata:
      labels:
        app: neu-inference
    spec:
      containers:
        - name: neu-inference
          image: neu-inference:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
